<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Vestigium.Controls</RootNamespace>
    <AssemblyName>Vestigium.Controls</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vestigium.Controls.StatusBar\Vestigium.Controls.StatusBar.csproj" />
    <ProjectReference Include="..\Vestigium.Controls.UnderConstruction\Vestigium.Controls.UnderConstruction.csproj" />
  </ItemGroup>
</Project>
