<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Vestigium.Controls.NumericUpDown</RootNamespace>
    <AssemblyName>Vestigium.Controls.NumericUpDown</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
